[package]
name = "giti"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.107"
serde = { version = "1.0.188", features = ["derive"] }
dirs = "5.0.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
